const express = require("express");
const app = express();
const port = 3000;

// Define different categories of quotes
const quoteCategories = {
  love: [
    "Love is not about possession. It's all about appreciation.",
    "In your smile, I see something more beautiful than the stars.",
    "To love and be loved is to feel the sun from both sides.",
    "You are the source of my joy, the center of my world, and the whole of my heart.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "Love is like a friendship caught on fire. In the beginning, a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
    "True love is not about perfection, it is hidden in flaws and imperfections.",
    "Love is the bridge between two hearts.",
    "Every love story is beautiful, but ours is my favorite.",
    "Love is not something you find. Love is something that finds you.",
    "Love is when you meet someone who tells you something new about yourself.",
    "I love you, not only for what you are but for what I am when I am with you.",
    "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds.",
    "Love is not just looking at each other, it's looking in the same direction.",
    "To the world, you may be one person, but to one person you may be the world.",
    "Love is like quicksilver in the hand. Leave the fingers open and it stays. Clutch it, and it darts away.",
    "The best thing to hold onto in life is each other.",
    "You know you're in love when you can't fall asleep because the reality is finally better than your dreams.",
    "Love is when the other person's happiness is more important than your own.",
    "I wish I could turn back the clock. I'd find you sooner and love you longer.",
    "Love is composed of a single soul inhabiting two bodies.",
    "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
    "Love is the master key that opens the gates of happiness.",
    "If I know what love is, it is because of you.",
    "The greatest happiness you can have is knowing that you are loved.",
    "Love cures people—both the ones who give it and the ones who receive it.",
    "Love is the only force capable of transforming an enemy into a friend.",
    "I am who I am because of you. You are every reason, every hope, and every dream I’ve ever had.",
    "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds.",
    "Love is like a friendship caught on fire. In the beginning, a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
    "True love is not about perfection, it is hidden in flaws and imperfections.",
    "I love you, not only for what you are but for what I am when I am with you.",
    "Love is not just a verb, it's you looking in the mirror.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "The best thing to hold onto in life is each other.",
    "The greatest thing you’ll ever learn is just to love and be loved in return.",
    "Love is like war: easy to begin but very hard to stop.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
    "Love is an act of endless forgiveness. A tender look which becomes a habit.",
    "To love oneself is the beginning of a lifelong romance.",
    "I love you without knowing how, or when, or from where. I love you straightforwardly, without complexities or pride; so I love you because I know no other way.",
    "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds.",
    "The water shines only by the sun. And it is you who are my sun.",
    "Love is a canvas furnished by nature and embroidered by imagination.",
    "In love, there is always one who kisses and one who offers the cheek.",
    "I would rather share one lifetime with you than face all the ages of this world alone.",
    "Love is not about possession. It's all about appreciation.",
    "I love you more than I have ever found a way to say to you.",
    "Love is not just a verb, it's you looking in the mirror.",
    "Love is when you meet someone who tells you something new about yourself.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
    "Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "The more I give to thee, the more I have, for both are infinite.",
    "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
    "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.",
    "Love is the joy of the good, the wonder of the wise, the amazement of the Gods.",
    "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    "Love is not an emotion, it's your very existence.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "Your love is all I need to feel complete.",
    "Love is the greatest refreshment in life.",
    "To love is nothing. To be loved is something. But to love and be loved, that’s everything.",
    "Love is like a friendship caught on fire. In the beginning, a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
    "True love is not about perfection, it is hidden in flaws and imperfections.",
    "I love you, not only for what you are but for what I am when I am with you.",
    "Love is not just a verb, it's you looking in the mirror.",
    "Love is when you meet someone who tells you something new about yourself.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
    "Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "The more I give to thee, the more I have, for both are infinite.",
    "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
    "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.",
    "Love is the joy of the good, the wonder of the wise, the amazement of the Gods.",
    "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    "Love is not an emotion, it's your very existence.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "Your love is all I need to feel complete.",
    "Love is the greatest refreshment in life.",
    "To love is nothing. To be loved is something. But to love and be loved, that’s everything.",
    "Love is like a friendship caught on fire. In the beginning, a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
    "True love is not about perfection, it is hidden in flaws and imperfections.",
    "I love you, not only for what you are but for what I am when I am with you.",
    "Love is not just a verb, it's you looking in the mirror.",
    "Love is when you meet someone who tells you something new about yourself.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
    "Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "The more I give to thee, the more I have, for both are infinite.",
    "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
    "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.",
    "Love is the joy of the good, the wonder of the wise, the amazement of the Gods.",
    "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    "Love is not an emotion, it's your very existence.",
    "Love is an endless mystery, for it has nothing else to explain it.",
    "Your love is all I need to feel complete.",
    "Love is the greatest refreshment in life.",
    "To love is nothing. To be loved is something. But to love and be loved, that’s everything.",
    "Love is like a friendship caught on fire. In the beginning, a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
  ],
  friendship: [
    "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'",
    "A true friend is someone who is always there for you, through the good times and the bad times.",
    "Friendship is the comfort of knowing that even when you feel alone, you aren't truly on your own.",
    "In the cookie of life, friends are the chocolate chips.",
    "A friend is someone who knows all about you and still loves you.",
    "Friendship is the key to unlocking the full potential of your heart.",
    "True friends are like stars; you don't always see them, but you know they're always there.",
    "Friends are the family we choose for ourselves.",
    "Friendship is the bridge that connects hearts across any distance.",
    "A good friend listens to your adventures, a best friend makes them with you.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friendship is the greatest gift that life has to offer.",
    "Friends are like stars – you don't always see them, but you know they're there.",
    "Friendship is the sweetest balm for the wounds of adversity.",
    "A friend is someone who understands your past, believes in your future, and accepts you just the way you are.",
    "Friendship is the golden thread that ties the heart of all the world.",
    "True friends are like diamonds – bright, beautiful, valuable, and always in style.",
    "In the garden of friendship, the best flowers are those of understanding and kindness.",
    "Friendship is the wine of life – it gets better as it grows older.",
    "A friend is someone you can call at any hour to laugh, to cry, or to complain.",
    "Good friends are like stars; you don't always see them, but you know they're always there.",
    "Friendship is the only cement that will ever hold the world together.",
    "A true friend is the greatest of all blessings.",
    "Friendship is the shadow of the evening, which increases with the setting sun of life.",
    "Friends are the siblings God never gave us.",
    "A friend is someone who knows the song in your heart and can sing it back to you even if you forget the words.",
    "Friendship is the rainbow between two hearts, sharing seven colors: love, sadness, happiness, truth, faith, secret, and respect.",
    "A true friend is the greatest of all blessings and the one that we take the least thought to acquire.",
    "Friendship is the only flower that blooms in all seasons.",
    "A true friend is someone who never gets tired of listening to your pointless dramas over and over again.",
    "Friendship is like standing on wet cement. The longer you stay, the harder it is to leave.",
    "Friends are like stars; you may not always see them, but you know they're always there.",
    "A friend is someone who knows everything about your life and still loves you.",
    "Friendship is the candle that lights up your heart whenever it is dark outside.",
    "A friend is one soul abiding in two bodies.",
    "Friendship is the only ship that will never sink.",
    "A true friend is someone who is always there, through the ups and downs, laughter and tears.",
    "Friends are the compass that guides us in life.",
    "Friendship is the joy in knowing there's someone who understands you perfectly.",
    "A real friend is someone who makes you feel like you're the only one.",
    "Friendship is like a star; even though you can't always see it, you know it's always there.",
    "A friend is one of the nicest things you can have, and one of the best things you can be.",
    "True friendship is like sound health; the value of it is seldom known until it is lost.",
    "Friendship is the most constant, the most enduring, and the most basic part of love.",
    "A friend is someone who knows the melody of your heart and can sing it back to you even if you forget the words.",
    "Friendship is the treasure that fills our hearts with laughter, joy, and warmth.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friends are the flowers in the garden of life.",
    "Friendship is the language of the heart, not spoken but understood.",
    "A friend is someone who knows you and still loves you.",
    "Friendship is the glue that holds life and faith together.",
    "A friend is one who believes in you when you have ceased to believe in yourself.",
    "Friends are like stars – you may not always see them, but you know they're always there.",
    "Friendship is the melody that soothes the soul.",
    "A real friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.",
    "Friends are like pillars on your porch. Sometimes they hold you up, sometimes they lean on you, and sometimes it's just enough to know they're standing by.",
    "Friendship is the only cement that will ever hold the world together.",
    "A friend is someone who knows all about you and still loves you.",
    "Friends are the family you choose for yourself.",
    "Friendship is the only rose without thorns.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friends are the stars that light up your darkest nights.",
    "Friendship is the rhythm that beats in the heart of every true connection.",
    "A friend is someone who gives you total freedom to be yourself.",
    "Friends are like diamonds – bright, beautiful, valuable, and always in style.",
    "Friendship is the bridge that connects hearts across any distance.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friends are like flowers in the garden of life.",
    "Friendship is the thread that ties our hearts together.",
    "A friend is someone who knows the song in your heart and can sing it back to you even if you forget the words.",
    "Friends are the family we choose for ourselves.",
    "Friendship is the sweetest balm for the wounds of adversity.",
    "A real friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.",
    "Friends are the stars that light up your darkest nights.",
    "Friendship is the only rose without thorns.",
    "A friend is someone who gives you total freedom to be yourself.",
    "Friends are the family you choose for yourself.",
    "Friendship is the rhythm that beats in the heart of every true connection.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friends are like diamonds – bright, beautiful, valuable, and always in style.",
    "Friendship is the bridge that connects hearts across any distance.",
    "A friend is someone who knows the song in your heart and can sing it back to you even if you forget the words.",
    "Friends are the family we choose for ourselves.",
    "Friendship is the sweetest balm for the wounds of adversity.",
    "A real friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.",
    "Friends are the stars that light up your darkest nights.",
    "Friendship is the only rose without thorns.",
    "A friend is someone who gives you total freedom to be yourself.",
    "Friends are the family you choose for yourself.",
    "Friendship is the rhythm that beats in the heart of every true connection.",
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friends are like diamonds – bright, beautiful, valuable, and always in style.",
    "Friendship is the bridge that connects hearts across any distance.",
    "A friend is someone who knows the song in your heart and can sing it back to you even if you forget the words.",
    "Friends are the family we choose for ourselves.",
    "Friendship is the sweetest balm for the wounds of adversity.",
    "A real friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.",
    "Friends are the stars that light up your darkest nights.",
    "Friendship is the only rose without thorns.",
    "A friend is someone who gives you total freedom to be yourself.",
  ],
  inspirational: [
    "Believe you can, and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best way to predict the future is to create it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "The only person you are destined to become is the person you decide to be.",
    "It's not whether you get knocked down, it's whether you get up.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don't take.",
    "The only way to achieve the impossible is to believe it is possible.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It always seems impossible until it's done.",
    "The best way to predict the future is to create it.",
    "Believe you can, and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best way to predict the future is to create it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "The only person you are destined to become is the person you decide to be.",
    "It's not whether you get knocked down, it's whether you get up.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don't take.",
    "The only way to achieve the impossible is to believe it is possible.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It always seems impossible until it's done.",
    "The best way to predict the future is to create it.",
    "Believe you can, and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best way to predict the future is to create it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "The only person you are destined to become is the person you decide to be.",
    "It's not whether you get knocked down, it's whether you get up.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don't take.",
    "The only way to achieve the impossible is to believe it is possible.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It always seems impossible until it's done.",
    "The best way to predict the future is to create it.",
    "Believe you can, and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best way to predict the future is to create it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "The only person you are destined to become is the person you decide to be.",
    "It's not whether you get knocked down, it's whether you get up.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don't take.",
    "The only way to achieve the impossible is to believe it is possible.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It always seems impossible until it's done.",
    "The best way to predict the future is to create it.",
    "Believe you can, and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
  ],
  funny: [
    "I'm on a whiskey diet. I've lost three days already.",
    "The early bird might get the worm, but the second mouse gets the cheese.",
    "Common sense is like deodorant. The people who need it most never use it.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I used to be a people person, but people ruined that for me.",
    "I'm not lazy, I'm on energy-saving mode.",
    "The only exercise I get is jumping to conclusions.",
    "I'm not short; I'm just more down to earth than most people.",
    "The secret of getting ahead is getting started, but the secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and then starting on the first one.",
    "I'm not shy; I'm just holding back my awesomeness so I don't intimidate you.",
    "My bed is a magical place where I suddenly remember everything I was supposed to do.",
    "I'm not clumsy. It's just that the floor hates me, the tables and chairs are bullies, and the wall gets in my way.",
    "I'm not addicted to coffee; we're just in a committed relationship.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "I don't need a hairstylist; my pillow gives me a new hairstyle every morning.",
    "I'm not a complete idiot; some parts are missing.",
    "I'm not lazy; I'm in energy-saving mode.",
    "I put the 'pro' in procrastinate.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not a morning person. I'm a not-a-morning-person person.",
    "My wife says I never listen to her, or something like that.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "I'm not old; I'm just retro.",
    "I finally realized that growing up is overrated. Good call, Peter Pan.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm not a chef; I just play one on TV.",
    "My bed is a magical place where I suddenly remember everything I was supposed to do.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm not a baker because I love kneading dough. I'm a baker because I love eating cookies.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I'm not fat; I'm just easier to see.",
    "I don't always lose my phone, but when I do, it's always on silent.",
    "I'm not short; I'm fun-sized.",
    "I'm not lazy; I'm in energy-saving mode.",
    "I'm not arguing; I'm just explaining why I'm right.",
    "I used to be a people person, but people ruined that for me.",
    "I'm not clumsy; the floor just hates me.",
    "I'm not a complete idiot; some parts are missing.",
    "I'm not a morning person. I'm not an afternoon person. I'm barely an evening person.",
    "I'm not a chef; I just play one on TV.",
    "I'm not saying I hate you, but if you were on fire and I had water, I'd drink it.",
    "I'm not lazy; I'm just on energy-saving mode.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not old; I'm just retro.",
    "I finally realized that growing up is overrated. Good call, Peter Pan.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm not a chef; I just play one on TV.",
    "My bed is a magical place where I suddenly remember everything I was supposed to do.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm not a baker because I love kneading dough. I'm a baker because I love eating cookies.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I'm not fat; I'm just easier to see.",
    "I don't always lose my phone, but when I do, it's always on silent.",
    "I'm not short; I'm fun-sized.",
    "I'm not lazy; I'm in energy-saving mode.",
    "I'm not arguing; I'm just explaining why I'm right.",
    "I used to be a people person, but people ruined that for me.",
    "I'm not clumsy; the floor just hates me.",
    "I'm not a complete idiot; some parts are missing.",
    "I'm not a morning person. I'm not an afternoon person. I'm barely an evening person.",
    "I'm not a chef; I just play one on TV.",
    "I'm not saying I hate you, but if you were on fire and I had water, I'd drink it.",
    "I'm not lazy; I'm just on energy-saving mode.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not old; I'm just retro.",
    "I finally realized that growing up is overrated. Good call, Peter Pan.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm not a chef; I just play one on TV.",
    "My bed is a magical place where I suddenly remember everything I was supposed to do.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm not a baker because I love kneading dough. I'm a baker because I love eating cookies.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I'm not fat; I'm just easier to see.",
    "I don't always lose my phone, but when I do, it's always on silent.",
    "I'm not short; I'm fun-sized.",
    "I'm not lazy; I'm in energy-saving mode.",
    "I'm not arguing; I'm just explaining why I'm right.",
    "I used to be a people person, but people ruined that for me.",
    "I'm not clumsy; the floor just hates me.",
    "I'm not a complete idiot; some parts are missing.",
    "I'm not a morning person. I'm not an afternoon person. I'm barely an evening person.",
    "I'm not a chef; I just play one on TV.",
    "I'm not saying I hate you, but if you were on fire and I had water, I'd drink it.",
    "I'm not lazy; I'm just on energy-saving mode.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not old; I'm just retro.",
    "I finally realized that growing up is overrated. Good call, Peter Pan.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm not a chef; I just play one on TV.",
    "My bed is a magical place where I suddenly remember everything I was supposed to do.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm not a baker because I love kneading dough. I'm a baker because I love eating cookies.",
    "I'm not lazy; I'm just on my energy-saving mode.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I'm not fat; I'm just easier to see.",
    "I don't always lose my phone, but when I do, it's always on silent.",
  ],
};

function getRandomItem(array) {
  return array[Math.floor(Math.random() * array.length)];
}

app.get("/api/randomquotes", (req, res) => {
  const singleQuotes = {};

  for (const category in quoteCategories) {
    if (quoteCategories.hasOwnProperty(category)) {
      const quotes = quoteCategories[category];
      const randomQuote = getRandomItem(quotes);
      singleQuotes[`${category}_quote`] = randomQuote;
    }
  }
  const jsonString = JSON.stringify(singleQuotes, null, 2);
  res.set("Content-Type", "application/json");
  res.send(jsonString);
});

app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}/api/randomquotes`);
});
